### PR TITLE
fix for cases when calling changeLanguage before finished to initialized

### LINKED ISSUE #1552: fallbackLng as default lng
Why did you change the behavior in the patch version?

19.8.5 - "use fallbackLng as default lng"

After update, language is always taken from "fallbackLng"
image

The behavior can be viewed in this repository
https://github.com/ogarich89/iso/tree/feature/i18next

### PR DESCRIPTION
**Pull request by adrai**
should fix #1552

#### Checklist

- [x] only relevant code is changed (make a diff before you submit the PR)
- [x] run tests `npm run test`
- [ ] tests are included
- [ ] documentation is changed or added

### CODE REVIEW

File: src/i18next.js [hunk 1]
```diff
@@ -154,14 +154,17 @@ class I18n extends EventEmitter {
...
         this.isInitialized = true;
         if (!this.options.isClone) this.logger.log('initialized', this.options);
         this.emit('initialized', this.options);
 
         deferred.resolve(t); // not rejecting on err (as err is only a loading translation failed warning)
         callback(err, t);
-      });
+      };
+      // fix for use cases when calling changeLanguage before finished to initialized (i.e. https://github.com/i18next/i18next/issues/1552)
+      if (this.languages && this.options.compatibilityAPI !== 'v1') return finish(null, this.t.bind(this));
```
Comment (jamuhl) [inline src/i18next.js:166]: is it API v1? v1 is more the v1 of i18next...this change was more v?!

Comment (adrai) [reply src/i18next.js:166]: this is just because of the v1 tests
